// name: SignalHandler.hh
// date: 25 Jul 14
// auth: Zach Hartwig
// mail: hartwig@psfc.mit.edu
//
// desc: The SignalHandler class contains the "slot" methods that are
//       triggered by "signals" generated by widgets in the
//       InterfaceBuilder class. It provides a modular way to handle
//       widget actions.
#ifndef __SignalHandler_hh__
#define __SignalHandler_hh__ 1

#include <TObject.h>

class InterfaceBuilder;


class SignalHandler : public TObject
{
public:
  SignalHandler(InterfaceBuilder *);
  ~SignalHandler();

  void HandleTextButtons();
  void HandleTerminate();
  
  // Register the class with ROOT
  ClassDef(SignalHandler, 0);
  
private:
  InterfaceBuilder *TheInterface;
};

#endif
